baseurl = "http://www.jeffsmithdev.com/"
languageCode = "en-us"
title = "Jeff Smith"
googleAnalytics = "UA-38942776-19"
Paginate = 1000

[params]
    description = "Jeff Smith"
    keywords = "Kotlin, DevOps, Qt, Programming, SysAdmin, Java, Javascript, Games, Tech Notes"